# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import booking_pb2 as booking__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in booking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllBookings = channel.unary_unary(
                '/Booking/GetAllBookings',
                request_serializer=booking__pb2.BookingEmpty.SerializeToString,
                response_deserializer=booking__pb2.Bookings.FromString,
                _registered_method=True)
        self.GetUserBookings = channel.unary_unary(
                '/Booking/GetUserBookings',
                request_serializer=booking__pb2.UserId.SerializeToString,
                response_deserializer=booking__pb2.Bookings.FromString,
                _registered_method=True)
        self.AddBookingOfUser = channel.unary_unary(
                '/Booking/AddBookingOfUser',
                request_serializer=booking__pb2.BookingItem.SerializeToString,
                response_deserializer=booking__pb2.Message.FromString,
                _registered_method=True)
        self.GetScheduleByDateB = channel.unary_unary(
                '/Booking/GetScheduleByDateB',
                request_serializer=booking__pb2.BDate.SerializeToString,
                response_deserializer=booking__pb2.BSchedule.FromString,
                _registered_method=True)
        self.GetMovieScheduleB = channel.unary_unary(
                '/Booking/GetMovieScheduleB',
                request_serializer=booking__pb2.BMovieID.SerializeToString,
                response_deserializer=booking__pb2.BMovieSchedule.FromString,
                _registered_method=True)


class BookingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllBookings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserBookings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBookingOfUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScheduleByDateB(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMovieScheduleB(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllBookings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllBookings,
                    request_deserializer=booking__pb2.BookingEmpty.FromString,
                    response_serializer=booking__pb2.Bookings.SerializeToString,
            ),
            'GetUserBookings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserBookings,
                    request_deserializer=booking__pb2.UserId.FromString,
                    response_serializer=booking__pb2.Bookings.SerializeToString,
            ),
            'AddBookingOfUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBookingOfUser,
                    request_deserializer=booking__pb2.BookingItem.FromString,
                    response_serializer=booking__pb2.Message.SerializeToString,
            ),
            'GetScheduleByDateB': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScheduleByDateB,
                    request_deserializer=booking__pb2.BDate.FromString,
                    response_serializer=booking__pb2.BSchedule.SerializeToString,
            ),
            'GetMovieScheduleB': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMovieScheduleB,
                    request_deserializer=booking__pb2.BMovieID.FromString,
                    response_serializer=booking__pb2.BMovieSchedule.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Booking', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Booking', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Booking(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Booking/GetAllBookings',
            booking__pb2.BookingEmpty.SerializeToString,
            booking__pb2.Bookings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Booking/GetUserBookings',
            booking__pb2.UserId.SerializeToString,
            booking__pb2.Bookings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddBookingOfUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Booking/AddBookingOfUser',
            booking__pb2.BookingItem.SerializeToString,
            booking__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScheduleByDateB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Booking/GetScheduleByDateB',
            booking__pb2.BDate.SerializeToString,
            booking__pb2.BSchedule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMovieScheduleB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Booking/GetMovieScheduleB',
            booking__pb2.BMovieID.SerializeToString,
            booking__pb2.BMovieSchedule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
