# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: booking.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'booking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"\x0e\n\x0c\x42ookingEmpty\"*\n\x08\x42ookings\x12\x1e\n\x08\x62ookings\x18\x01 \x03(\x0b\x32\x0c.BookingItem\"\x14\n\x06UserId\x12\n\n\x02id\x18\x01 \x01(\t\"8\n\x0b\x42ookingItem\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\r\n\x05movie\x18\x03 \x01(\t\"\x17\n\x07Message\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t2\x8e\x01\n\x07\x42ooking\x12,\n\x0eGetAllBookings\x12\r.BookingEmpty\x1a\t.Bookings\"\x00\x12\'\n\x0fGetUserBookings\x12\x07.UserId\x1a\t.Bookings\"\x00\x12,\n\x10\x41\x64\x64\x42ookingOfUser\x12\x0c.BookingItem\x1a\x08.Message\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKINGEMPTY']._serialized_start=17
  _globals['_BOOKINGEMPTY']._serialized_end=31
  _globals['_BOOKINGS']._serialized_start=33
  _globals['_BOOKINGS']._serialized_end=75
  _globals['_USERID']._serialized_start=77
  _globals['_USERID']._serialized_end=97
  _globals['_BOOKINGITEM']._serialized_start=99
  _globals['_BOOKINGITEM']._serialized_end=155
  _globals['_MESSAGE']._serialized_start=157
  _globals['_MESSAGE']._serialized_end=180
  _globals['_BOOKING']._serialized_start=183
  _globals['_BOOKING']._serialized_end=325
# @@protoc_insertion_point(module_scope)
